services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:admin123@db:3306/trading_bot
      - API_BASE_URL=http://api:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trading-network

  interface:
    build: 
      context: .
      dockerfile: interface/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    networks:
      - trading-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=trading_bot
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin123"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  trading-network:
    driver: bridge

volumes:
  mysql-data: 