[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
runOnSave = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = false

[logger]
level = "error"

[ui]
hideSidebarNav = true 