name: Deploy API to Azure Container Registry

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'run.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - '!interface/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3FB1C43ABA1D433CA125F5305E226A0F }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_068A327B363545F28830F0DFE7ACADBF }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B44DE00CB69E4C3BBBEF251BBA10BD70 }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ibmecdockerimage.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push API image
      run: |
        docker build -t ibmecdockerimage.azurecr.io/projeto-cloud-202501-api:latest .
        docker push ibmecdockerimage.azurecr.io/projeto-cloud-202501-api:latest 