name: Deploy API to Azure Web App

on:
  push:
    branches: [ interface ]
    paths:
      - 'app/**'
      - 'run.py'
      - 'requirements.txt'
      - '.deployment'
      - '!interface/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Zip artifact for deployment
      run: |
        zip release.zip ./* -r -x "interface/*" -x "run_interface.py"

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: api-app
        path: |
          release.zip
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: api-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3FB1C43ABA1D433CA125F5305E226A0F }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_068A327B363545F28830F0DFE7ACADBF }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B44DE00CB69E4C3BBBEF251BBA10BD70 }}

    - name: Deploy to Azure Web App (API)
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: ${{ secrets.AZURE_API_APP_NAME }}
        slot-name: 'Production' 