name: Deploy Interface to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'interface/**'
      - 'run_interface.py'
      - '!app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r interface/requirements.txt
    
    - name: Zip artifact for deployment
      run: |
        # Criar uma estrutura temporária para o deploy
        mkdir -p deploy_temp
        # Copiar apenas os arquivos necessários
        cp -r interface/* deploy_temp/
        cp run_interface.py deploy_temp/
        # Entrar na pasta temporária e zipar
        cd deploy_temp
        zip -r ../release.zip .

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: interface-app
        path: |
          release.zip
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: interface-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_46909BA0C91247B38E6206AB6712BB5C }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5EF9AAB8813D40098C11678B4DFFCE3F }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBB69C55025244499429F441458764A0 }}

    - name: Deploy to Azure Web App (Interface)
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: 'ibmec-trading-bot-interface'
        slot-name: 'Production' 