name: Deploy Interface to Azure Container Registry 

on:
  push:
    branches: [ main ]
    paths:
      - 'interface/**'
      - 'interface/Dockerfile'
      - '!app/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_46909BA0C91247B38E6206AB6712BB5C }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5EF9AAB8813D40098C11678B4DFFCE3F }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBB69C55025244499429F441458764A0 }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ibmecdockerimage.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Interface image
      run: |
        docker build -t ibmecdockerimage.azurecr.io/projeto-cloud-202501-interface:latest -f interface/Dockerfile .
        docker push ibmecdockerimage.azurecr.io/projeto-cloud-202501-interface:latest 