name: Deploy Interface to Azure Container Registry

on:
  push:
    branches: [ main ]
    paths:
      - 'interface/**'
      - 'interface/Dockerfile'
      - '!app/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ibmecdockerimage.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Interface image
      run: |
        docker build -t ibmecdockerimage.azurecr.io/projeto-cloud-202501-interface:latest -f interface/Dockerfile .
        docker push ibmecdockerimage.azurecr.io/projeto-cloud-202501-interface:latest 